# Jekyll
exclude:

name: Phumbler
baseurl: /
permalink: /blog/:year/:month/:day/:title/

tagline: Phumbler

navigation:
- text: Home
  url: /
  alt_url: /index.html
  layout: default
- text: Support
  url: mailto:support@phumbler.com
  layout: none
